### ISSUE TITLE
Plus and minus does not work If a product is using OPTIONS

### ISSUE THREAD

**Issue by Rodien** [openstore-ecommerce/OpenStore#264] opened 2022-04-07 18:41 UTC
When using options you wont be able to use plus or minus in the cart.

DNN 9.8.1
OpenStore  4.1.11
NBrightTemplateSys 8.6.3
 

![image](https://user-images.githubusercontent.com/50739829/162273665-9eadd947-739c-4de1-b779-b5996acef00a.png)

![image](https://user-images.githubusercontent.com/50739829/162273996-ab5050f2-eaa7-4e0e-b58e-8ec767ecf128.png)

**Comment by DNNMonster** [comment] 2022-04-07 22:00
Is there a js error showing in your browser's developer window?

**Comment by Rodien** [comment] 2022-04-07 22:03
No, no errors...

**Comment by DNNMonster** [comment] 2022-04-07 22:20
You might try placing a break point in the cart.js in either the .qtyminus or .qtyplus click funcs to see if you can diagnose what's happening.  I am not reproducing this error so it's possible this is data related.  Maybe the item code..??

**Comment by DNNMonster** [comment] 2022-04-08 16:53
I am seeing this issue now but I have not identified the cause.

**Comment by DNNMonster** [comment] 2022-04-08 17:12
I think this is due to the colon that is found in the item code for products in carts which have options.  We need to escape the colon so JQuery can find the target to update.

**Comment by Rodien** [comment] 2022-04-08 20:15
Ahh I see, I was looking into it too but I was not having much success. 

Thanks for looking into it.

**Comment by DNNMonster** [comment] 2022-04-09 02:29
Cool. Let's close this up but we can re-open it if needed.

**Closed by DNNMonster** 2022-04-09 02:29 UTC
